run:
  timeout: 10m
linters:
  disable-all: true
  enable:
    - ineffassign
    - typecheck
    - gosimple
    - goimports
    # - errcheck
    # - stylecheck
    - asciicheck
    - exportloopref
    # - staticcheck
    - makezero
    - prealloc
    - predeclared
    - misspell
    - unconvert
    - govet
    - gocritic
    - bodyclose

linters-settings:
  gocritic:
    enabled-checks:
      # Diagnostic
      - sloppyReassign
      - weakCond

      # Performance
      - appendCombine
      - equalFold
      - hugeParam
      - indexAlloc
      - rangeExprCopy
      - rangeValCopy
      - sliceClear
      - stringXbytes

      # Style
      - boolExprSimplify
      - elseif
      - emptyFallthrough
      # - emptyStringTest
      - hexLiteral
      - methodExprCall
      - typeAssertChain

      # Opinionated
      - builtinShadow
      - importShadow
      - initClause
      - nestingReduce
      - ptrToRefParam
      - typeUnparen
      - unnecessaryBlock