// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: hstream.proto

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HStreamApiClient is the client API for HStreamApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HStreamApiClient interface {
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	// Stream APIs
	CreateStream(ctx context.Context, in *Stream, opts ...grpc.CallOption) (*Stream, error)
	DeleteStream(ctx context.Context, in *DeleteStreamRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListStreams(ctx context.Context, in *ListStreamsRequest, opts ...grpc.CallOption) (*ListStreamsResponse, error)
	LookupShard(ctx context.Context, in *LookupShardRequest, opts ...grpc.CallOption) (*LookupShardResponse, error)
	Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error)
	// Shard APIs
	ListShards(ctx context.Context, in *ListShardsRequest, opts ...grpc.CallOption) (*ListShardsResponse, error)
	CreateShardReader(ctx context.Context, in *CreateShardReaderRequest, opts ...grpc.CallOption) (*CreateShardReaderResponse, error)
	LookupShardReader(ctx context.Context, in *LookupShardReaderRequest, opts ...grpc.CallOption) (*LookupShardReaderResponse, error)
	ReadShard(ctx context.Context, in *ReadShardRequest, opts ...grpc.CallOption) (*ReadShardResponse, error)
	DeleteShardReader(ctx context.Context, in *DeleteShardReaderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Subscribe APIs
	CreateSubscription(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (*Subscription, error)
	ListSubscriptions(ctx context.Context, in *ListSubscriptionsRequest, opts ...grpc.CallOption) (*ListSubscriptionsResponse, error)
	CheckSubscriptionExist(ctx context.Context, in *CheckSubscriptionExistRequest, opts ...grpc.CallOption) (*CheckSubscriptionExistResponse, error)
	DeleteSubscription(ctx context.Context, in *DeleteSubscriptionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	LookupSubscription(ctx context.Context, in *LookupSubscriptionRequest, opts ...grpc.CallOption) (*LookupSubscriptionResponse, error)
	StreamingFetch(ctx context.Context, opts ...grpc.CallOption) (HStreamApi_StreamingFetchClient, error)
	// Cluster APIs
	DescribeCluster(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DescribeClusterResponse, error)
	// Admin Command
	SendAdminCommand(ctx context.Context, in *AdminCommandRequest, opts ...grpc.CallOption) (*AdminCommandResponse, error)
	// Stats
	PerStreamTimeSeriesStats(ctx context.Context, in *PerStreamTimeSeriesStatsRequest, opts ...grpc.CallOption) (*PerStreamTimeSeriesStatsResponse, error)
	PerStreamTimeSeriesStatsAll(ctx context.Context, in *PerStreamTimeSeriesStatsAllRequest, opts ...grpc.CallOption) (*PerStreamTimeSeriesStatsAllResponse, error)
	// only for push query
	// e.g., select (with emit changes)
	ExecutePushQuery(ctx context.Context, in *CommandPushQuery, opts ...grpc.CallOption) (HStreamApi_ExecutePushQueryClient, error)
	// for execute any sql stmt except push query,
	// e.g., insert, create, show/list, select(without emit changes) ...
	ExecuteQuery(ctx context.Context, in *CommandQuery, opts ...grpc.CallOption) (*CommandQueryResponse, error)
	// query related apis
	ListQueries(ctx context.Context, in *ListQueriesRequest, opts ...grpc.CallOption) (*ListQueriesResponse, error)
	GetQuery(ctx context.Context, in *GetQueryRequest, opts ...grpc.CallOption) (*Query, error)
	TerminateQueries(ctx context.Context, in *TerminateQueriesRequest, opts ...grpc.CallOption) (*TerminateQueriesResponse, error)
	DeleteQuery(ctx context.Context, in *DeleteQueryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RestartQuery(ctx context.Context, in *RestartQueryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// connector related apis
	CreateConnector(ctx context.Context, in *CreateConnectorRequest, opts ...grpc.CallOption) (*Connector, error)
	ListConnectors(ctx context.Context, in *ListConnectorsRequest, opts ...grpc.CallOption) (*ListConnectorsResponse, error)
	GetConnector(ctx context.Context, in *GetConnectorRequest, opts ...grpc.CallOption) (*Connector, error)
	DeleteConnector(ctx context.Context, in *DeleteConnectorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PauseConnector(ctx context.Context, in *PauseConnectorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ResumeConnector(ctx context.Context, in *ResumeConnectorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	LookupConnector(ctx context.Context, in *LookupConnectorRequest, opts ...grpc.CallOption) (*LookupConnectorResponse, error)
	// view related apis
	ListViews(ctx context.Context, in *ListViewsRequest, opts ...grpc.CallOption) (*ListViewsResponse, error)
	GetView(ctx context.Context, in *GetViewRequest, opts ...grpc.CallOption) (*View, error)
	DeleteView(ctx context.Context, in *DeleteViewRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// FIXME: (store)node related apis
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*Node, error)
}

type hStreamApiClient struct {
	cc grpc.ClientConnInterface
}

func NewHStreamApiClient(cc grpc.ClientConnInterface) HStreamApiClient {
	return &hStreamApiClient{cc}
}

func (c *hStreamApiClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) CreateStream(ctx context.Context, in *Stream, opts ...grpc.CallOption) (*Stream, error) {
	out := new(Stream)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/CreateStream", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) DeleteStream(ctx context.Context, in *DeleteStreamRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/DeleteStream", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) ListStreams(ctx context.Context, in *ListStreamsRequest, opts ...grpc.CallOption) (*ListStreamsResponse, error) {
	out := new(ListStreamsResponse)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/ListStreams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) LookupShard(ctx context.Context, in *LookupShardRequest, opts ...grpc.CallOption) (*LookupShardResponse, error) {
	out := new(LookupShardResponse)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/LookupShard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error) {
	out := new(AppendResponse)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/Append", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) ListShards(ctx context.Context, in *ListShardsRequest, opts ...grpc.CallOption) (*ListShardsResponse, error) {
	out := new(ListShardsResponse)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/ListShards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) CreateShardReader(ctx context.Context, in *CreateShardReaderRequest, opts ...grpc.CallOption) (*CreateShardReaderResponse, error) {
	out := new(CreateShardReaderResponse)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/CreateShardReader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) LookupShardReader(ctx context.Context, in *LookupShardReaderRequest, opts ...grpc.CallOption) (*LookupShardReaderResponse, error) {
	out := new(LookupShardReaderResponse)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/LookupShardReader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) ReadShard(ctx context.Context, in *ReadShardRequest, opts ...grpc.CallOption) (*ReadShardResponse, error) {
	out := new(ReadShardResponse)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/ReadShard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) DeleteShardReader(ctx context.Context, in *DeleteShardReaderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/DeleteShardReader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) CreateSubscription(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (*Subscription, error) {
	out := new(Subscription)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/CreateSubscription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) ListSubscriptions(ctx context.Context, in *ListSubscriptionsRequest, opts ...grpc.CallOption) (*ListSubscriptionsResponse, error) {
	out := new(ListSubscriptionsResponse)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/ListSubscriptions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) CheckSubscriptionExist(ctx context.Context, in *CheckSubscriptionExistRequest, opts ...grpc.CallOption) (*CheckSubscriptionExistResponse, error) {
	out := new(CheckSubscriptionExistResponse)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/CheckSubscriptionExist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) DeleteSubscription(ctx context.Context, in *DeleteSubscriptionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/DeleteSubscription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) LookupSubscription(ctx context.Context, in *LookupSubscriptionRequest, opts ...grpc.CallOption) (*LookupSubscriptionResponse, error) {
	out := new(LookupSubscriptionResponse)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/LookupSubscription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) StreamingFetch(ctx context.Context, opts ...grpc.CallOption) (HStreamApi_StreamingFetchClient, error) {
	stream, err := c.cc.NewStream(ctx, &HStreamApi_ServiceDesc.Streams[0], "/hstream.server.HStreamApi/StreamingFetch", opts...)
	if err != nil {
		return nil, err
	}
	x := &hStreamApiStreamingFetchClient{stream}
	return x, nil
}

type HStreamApi_StreamingFetchClient interface {
	Send(*StreamingFetchRequest) error
	Recv() (*StreamingFetchResponse, error)
	grpc.ClientStream
}

type hStreamApiStreamingFetchClient struct {
	grpc.ClientStream
}

func (x *hStreamApiStreamingFetchClient) Send(m *StreamingFetchRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *hStreamApiStreamingFetchClient) Recv() (*StreamingFetchResponse, error) {
	m := new(StreamingFetchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hStreamApiClient) DescribeCluster(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DescribeClusterResponse, error) {
	out := new(DescribeClusterResponse)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/DescribeCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) SendAdminCommand(ctx context.Context, in *AdminCommandRequest, opts ...grpc.CallOption) (*AdminCommandResponse, error) {
	out := new(AdminCommandResponse)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/SendAdminCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) PerStreamTimeSeriesStats(ctx context.Context, in *PerStreamTimeSeriesStatsRequest, opts ...grpc.CallOption) (*PerStreamTimeSeriesStatsResponse, error) {
	out := new(PerStreamTimeSeriesStatsResponse)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/PerStreamTimeSeriesStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) PerStreamTimeSeriesStatsAll(ctx context.Context, in *PerStreamTimeSeriesStatsAllRequest, opts ...grpc.CallOption) (*PerStreamTimeSeriesStatsAllResponse, error) {
	out := new(PerStreamTimeSeriesStatsAllResponse)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/PerStreamTimeSeriesStatsAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) ExecutePushQuery(ctx context.Context, in *CommandPushQuery, opts ...grpc.CallOption) (HStreamApi_ExecutePushQueryClient, error) {
	stream, err := c.cc.NewStream(ctx, &HStreamApi_ServiceDesc.Streams[1], "/hstream.server.HStreamApi/ExecutePushQuery", opts...)
	if err != nil {
		return nil, err
	}
	x := &hStreamApiExecutePushQueryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HStreamApi_ExecutePushQueryClient interface {
	Recv() (*structpb.Struct, error)
	grpc.ClientStream
}

type hStreamApiExecutePushQueryClient struct {
	grpc.ClientStream
}

func (x *hStreamApiExecutePushQueryClient) Recv() (*structpb.Struct, error) {
	m := new(structpb.Struct)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hStreamApiClient) ExecuteQuery(ctx context.Context, in *CommandQuery, opts ...grpc.CallOption) (*CommandQueryResponse, error) {
	out := new(CommandQueryResponse)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/ExecuteQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) ListQueries(ctx context.Context, in *ListQueriesRequest, opts ...grpc.CallOption) (*ListQueriesResponse, error) {
	out := new(ListQueriesResponse)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/ListQueries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) GetQuery(ctx context.Context, in *GetQueryRequest, opts ...grpc.CallOption) (*Query, error) {
	out := new(Query)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/GetQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) TerminateQueries(ctx context.Context, in *TerminateQueriesRequest, opts ...grpc.CallOption) (*TerminateQueriesResponse, error) {
	out := new(TerminateQueriesResponse)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/TerminateQueries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) DeleteQuery(ctx context.Context, in *DeleteQueryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/DeleteQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) RestartQuery(ctx context.Context, in *RestartQueryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/RestartQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) CreateConnector(ctx context.Context, in *CreateConnectorRequest, opts ...grpc.CallOption) (*Connector, error) {
	out := new(Connector)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/CreateConnector", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) ListConnectors(ctx context.Context, in *ListConnectorsRequest, opts ...grpc.CallOption) (*ListConnectorsResponse, error) {
	out := new(ListConnectorsResponse)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/ListConnectors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) GetConnector(ctx context.Context, in *GetConnectorRequest, opts ...grpc.CallOption) (*Connector, error) {
	out := new(Connector)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/GetConnector", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) DeleteConnector(ctx context.Context, in *DeleteConnectorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/DeleteConnector", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) PauseConnector(ctx context.Context, in *PauseConnectorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/PauseConnector", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) ResumeConnector(ctx context.Context, in *ResumeConnectorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/ResumeConnector", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) LookupConnector(ctx context.Context, in *LookupConnectorRequest, opts ...grpc.CallOption) (*LookupConnectorResponse, error) {
	out := new(LookupConnectorResponse)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/LookupConnector", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) ListViews(ctx context.Context, in *ListViewsRequest, opts ...grpc.CallOption) (*ListViewsResponse, error) {
	out := new(ListViewsResponse)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/ListViews", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) GetView(ctx context.Context, in *GetViewRequest, opts ...grpc.CallOption) (*View, error) {
	out := new(View)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/GetView", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) DeleteView(ctx context.Context, in *DeleteViewRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/DeleteView", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/ListNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hStreamApiClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := c.cc.Invoke(ctx, "/hstream.server.HStreamApi/GetNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HStreamApiServer is the server API for HStreamApi service.
// All implementations must embed UnimplementedHStreamApiServer
// for forward compatibility
type HStreamApiServer interface {
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	// Stream APIs
	CreateStream(context.Context, *Stream) (*Stream, error)
	DeleteStream(context.Context, *DeleteStreamRequest) (*emptypb.Empty, error)
	ListStreams(context.Context, *ListStreamsRequest) (*ListStreamsResponse, error)
	LookupShard(context.Context, *LookupShardRequest) (*LookupShardResponse, error)
	Append(context.Context, *AppendRequest) (*AppendResponse, error)
	// Shard APIs
	ListShards(context.Context, *ListShardsRequest) (*ListShardsResponse, error)
	CreateShardReader(context.Context, *CreateShardReaderRequest) (*CreateShardReaderResponse, error)
	LookupShardReader(context.Context, *LookupShardReaderRequest) (*LookupShardReaderResponse, error)
	ReadShard(context.Context, *ReadShardRequest) (*ReadShardResponse, error)
	DeleteShardReader(context.Context, *DeleteShardReaderRequest) (*emptypb.Empty, error)
	// Subscribe APIs
	CreateSubscription(context.Context, *Subscription) (*Subscription, error)
	ListSubscriptions(context.Context, *ListSubscriptionsRequest) (*ListSubscriptionsResponse, error)
	CheckSubscriptionExist(context.Context, *CheckSubscriptionExistRequest) (*CheckSubscriptionExistResponse, error)
	DeleteSubscription(context.Context, *DeleteSubscriptionRequest) (*emptypb.Empty, error)
	LookupSubscription(context.Context, *LookupSubscriptionRequest) (*LookupSubscriptionResponse, error)
	StreamingFetch(HStreamApi_StreamingFetchServer) error
	// Cluster APIs
	DescribeCluster(context.Context, *emptypb.Empty) (*DescribeClusterResponse, error)
	// Admin Command
	SendAdminCommand(context.Context, *AdminCommandRequest) (*AdminCommandResponse, error)
	// Stats
	PerStreamTimeSeriesStats(context.Context, *PerStreamTimeSeriesStatsRequest) (*PerStreamTimeSeriesStatsResponse, error)
	PerStreamTimeSeriesStatsAll(context.Context, *PerStreamTimeSeriesStatsAllRequest) (*PerStreamTimeSeriesStatsAllResponse, error)
	// only for push query
	// e.g., select (with emit changes)
	ExecutePushQuery(*CommandPushQuery, HStreamApi_ExecutePushQueryServer) error
	// for execute any sql stmt except push query,
	// e.g., insert, create, show/list, select(without emit changes) ...
	ExecuteQuery(context.Context, *CommandQuery) (*CommandQueryResponse, error)
	// query related apis
	ListQueries(context.Context, *ListQueriesRequest) (*ListQueriesResponse, error)
	GetQuery(context.Context, *GetQueryRequest) (*Query, error)
	TerminateQueries(context.Context, *TerminateQueriesRequest) (*TerminateQueriesResponse, error)
	DeleteQuery(context.Context, *DeleteQueryRequest) (*emptypb.Empty, error)
	RestartQuery(context.Context, *RestartQueryRequest) (*emptypb.Empty, error)
	// connector related apis
	CreateConnector(context.Context, *CreateConnectorRequest) (*Connector, error)
	ListConnectors(context.Context, *ListConnectorsRequest) (*ListConnectorsResponse, error)
	GetConnector(context.Context, *GetConnectorRequest) (*Connector, error)
	DeleteConnector(context.Context, *DeleteConnectorRequest) (*emptypb.Empty, error)
	PauseConnector(context.Context, *PauseConnectorRequest) (*emptypb.Empty, error)
	ResumeConnector(context.Context, *ResumeConnectorRequest) (*emptypb.Empty, error)
	LookupConnector(context.Context, *LookupConnectorRequest) (*LookupConnectorResponse, error)
	// view related apis
	ListViews(context.Context, *ListViewsRequest) (*ListViewsResponse, error)
	GetView(context.Context, *GetViewRequest) (*View, error)
	DeleteView(context.Context, *DeleteViewRequest) (*emptypb.Empty, error)
	// FIXME: (store)node related apis
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	GetNode(context.Context, *GetNodeRequest) (*Node, error)
	mustEmbedUnimplementedHStreamApiServer()
}

// UnimplementedHStreamApiServer must be embedded to have forward compatible implementations.
type UnimplementedHStreamApiServer struct {
}

func (UnimplementedHStreamApiServer) Echo(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedHStreamApiServer) CreateStream(context.Context, *Stream) (*Stream, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStream not implemented")
}
func (UnimplementedHStreamApiServer) DeleteStream(context.Context, *DeleteStreamRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStream not implemented")
}
func (UnimplementedHStreamApiServer) ListStreams(context.Context, *ListStreamsRequest) (*ListStreamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStreams not implemented")
}
func (UnimplementedHStreamApiServer) LookupShard(context.Context, *LookupShardRequest) (*LookupShardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookupShard not implemented")
}
func (UnimplementedHStreamApiServer) Append(context.Context, *AppendRequest) (*AppendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedHStreamApiServer) ListShards(context.Context, *ListShardsRequest) (*ListShardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListShards not implemented")
}
func (UnimplementedHStreamApiServer) CreateShardReader(context.Context, *CreateShardReaderRequest) (*CreateShardReaderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateShardReader not implemented")
}
func (UnimplementedHStreamApiServer) LookupShardReader(context.Context, *LookupShardReaderRequest) (*LookupShardReaderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookupShardReader not implemented")
}
func (UnimplementedHStreamApiServer) ReadShard(context.Context, *ReadShardRequest) (*ReadShardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadShard not implemented")
}
func (UnimplementedHStreamApiServer) DeleteShardReader(context.Context, *DeleteShardReaderRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteShardReader not implemented")
}
func (UnimplementedHStreamApiServer) CreateSubscription(context.Context, *Subscription) (*Subscription, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSubscription not implemented")
}
func (UnimplementedHStreamApiServer) ListSubscriptions(context.Context, *ListSubscriptionsRequest) (*ListSubscriptionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSubscriptions not implemented")
}
func (UnimplementedHStreamApiServer) CheckSubscriptionExist(context.Context, *CheckSubscriptionExistRequest) (*CheckSubscriptionExistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckSubscriptionExist not implemented")
}
func (UnimplementedHStreamApiServer) DeleteSubscription(context.Context, *DeleteSubscriptionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSubscription not implemented")
}
func (UnimplementedHStreamApiServer) LookupSubscription(context.Context, *LookupSubscriptionRequest) (*LookupSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookupSubscription not implemented")
}
func (UnimplementedHStreamApiServer) StreamingFetch(HStreamApi_StreamingFetchServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamingFetch not implemented")
}
func (UnimplementedHStreamApiServer) DescribeCluster(context.Context, *emptypb.Empty) (*DescribeClusterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeCluster not implemented")
}
func (UnimplementedHStreamApiServer) SendAdminCommand(context.Context, *AdminCommandRequest) (*AdminCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAdminCommand not implemented")
}
func (UnimplementedHStreamApiServer) PerStreamTimeSeriesStats(context.Context, *PerStreamTimeSeriesStatsRequest) (*PerStreamTimeSeriesStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PerStreamTimeSeriesStats not implemented")
}
func (UnimplementedHStreamApiServer) PerStreamTimeSeriesStatsAll(context.Context, *PerStreamTimeSeriesStatsAllRequest) (*PerStreamTimeSeriesStatsAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PerStreamTimeSeriesStatsAll not implemented")
}
func (UnimplementedHStreamApiServer) ExecutePushQuery(*CommandPushQuery, HStreamApi_ExecutePushQueryServer) error {
	return status.Errorf(codes.Unimplemented, "method ExecutePushQuery not implemented")
}
func (UnimplementedHStreamApiServer) ExecuteQuery(context.Context, *CommandQuery) (*CommandQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteQuery not implemented")
}
func (UnimplementedHStreamApiServer) ListQueries(context.Context, *ListQueriesRequest) (*ListQueriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListQueries not implemented")
}
func (UnimplementedHStreamApiServer) GetQuery(context.Context, *GetQueryRequest) (*Query, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuery not implemented")
}
func (UnimplementedHStreamApiServer) TerminateQueries(context.Context, *TerminateQueriesRequest) (*TerminateQueriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TerminateQueries not implemented")
}
func (UnimplementedHStreamApiServer) DeleteQuery(context.Context, *DeleteQueryRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteQuery not implemented")
}
func (UnimplementedHStreamApiServer) RestartQuery(context.Context, *RestartQueryRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartQuery not implemented")
}
func (UnimplementedHStreamApiServer) CreateConnector(context.Context, *CreateConnectorRequest) (*Connector, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConnector not implemented")
}
func (UnimplementedHStreamApiServer) ListConnectors(context.Context, *ListConnectorsRequest) (*ListConnectorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConnectors not implemented")
}
func (UnimplementedHStreamApiServer) GetConnector(context.Context, *GetConnectorRequest) (*Connector, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConnector not implemented")
}
func (UnimplementedHStreamApiServer) DeleteConnector(context.Context, *DeleteConnectorRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteConnector not implemented")
}
func (UnimplementedHStreamApiServer) PauseConnector(context.Context, *PauseConnectorRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseConnector not implemented")
}
func (UnimplementedHStreamApiServer) ResumeConnector(context.Context, *ResumeConnectorRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeConnector not implemented")
}
func (UnimplementedHStreamApiServer) LookupConnector(context.Context, *LookupConnectorRequest) (*LookupConnectorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookupConnector not implemented")
}
func (UnimplementedHStreamApiServer) ListViews(context.Context, *ListViewsRequest) (*ListViewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListViews not implemented")
}
func (UnimplementedHStreamApiServer) GetView(context.Context, *GetViewRequest) (*View, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetView not implemented")
}
func (UnimplementedHStreamApiServer) DeleteView(context.Context, *DeleteViewRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteView not implemented")
}
func (UnimplementedHStreamApiServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedHStreamApiServer) GetNode(context.Context, *GetNodeRequest) (*Node, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedHStreamApiServer) mustEmbedUnimplementedHStreamApiServer() {}

// UnsafeHStreamApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HStreamApiServer will
// result in compilation errors.
type UnsafeHStreamApiServer interface {
	mustEmbedUnimplementedHStreamApiServer()
}

func RegisterHStreamApiServer(s grpc.ServiceRegistrar, srv HStreamApiServer) {
	s.RegisterService(&HStreamApi_ServiceDesc, srv)
}

func _HStreamApi_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_CreateStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Stream)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).CreateStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/CreateStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).CreateStream(ctx, req.(*Stream))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_DeleteStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).DeleteStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/DeleteStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).DeleteStream(ctx, req.(*DeleteStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_ListStreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).ListStreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/ListStreams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).ListStreams(ctx, req.(*ListStreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_LookupShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).LookupShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/LookupShard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).LookupShard(ctx, req.(*LookupShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/Append",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).Append(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_ListShards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).ListShards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/ListShards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).ListShards(ctx, req.(*ListShardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_CreateShardReader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShardReaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).CreateShardReader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/CreateShardReader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).CreateShardReader(ctx, req.(*CreateShardReaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_LookupShardReader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupShardReaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).LookupShardReader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/LookupShardReader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).LookupShardReader(ctx, req.(*LookupShardReaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_ReadShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).ReadShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/ReadShard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).ReadShard(ctx, req.(*ReadShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_DeleteShardReader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShardReaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).DeleteShardReader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/DeleteShardReader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).DeleteShardReader(ctx, req.(*DeleteShardReaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_CreateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Subscription)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).CreateSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/CreateSubscription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).CreateSubscription(ctx, req.(*Subscription))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_ListSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubscriptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).ListSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/ListSubscriptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).ListSubscriptions(ctx, req.(*ListSubscriptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_CheckSubscriptionExist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckSubscriptionExistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).CheckSubscriptionExist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/CheckSubscriptionExist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).CheckSubscriptionExist(ctx, req.(*CheckSubscriptionExistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_DeleteSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).DeleteSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/DeleteSubscription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).DeleteSubscription(ctx, req.(*DeleteSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_LookupSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).LookupSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/LookupSubscription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).LookupSubscription(ctx, req.(*LookupSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_StreamingFetch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HStreamApiServer).StreamingFetch(&hStreamApiStreamingFetchServer{stream})
}

type HStreamApi_StreamingFetchServer interface {
	Send(*StreamingFetchResponse) error
	Recv() (*StreamingFetchRequest, error)
	grpc.ServerStream
}

type hStreamApiStreamingFetchServer struct {
	grpc.ServerStream
}

func (x *hStreamApiStreamingFetchServer) Send(m *StreamingFetchResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *hStreamApiStreamingFetchServer) Recv() (*StreamingFetchRequest, error) {
	m := new(StreamingFetchRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _HStreamApi_DescribeCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).DescribeCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/DescribeCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).DescribeCluster(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_SendAdminCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).SendAdminCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/SendAdminCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).SendAdminCommand(ctx, req.(*AdminCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_PerStreamTimeSeriesStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PerStreamTimeSeriesStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).PerStreamTimeSeriesStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/PerStreamTimeSeriesStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).PerStreamTimeSeriesStats(ctx, req.(*PerStreamTimeSeriesStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_PerStreamTimeSeriesStatsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PerStreamTimeSeriesStatsAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).PerStreamTimeSeriesStatsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/PerStreamTimeSeriesStatsAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).PerStreamTimeSeriesStatsAll(ctx, req.(*PerStreamTimeSeriesStatsAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_ExecutePushQuery_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CommandPushQuery)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HStreamApiServer).ExecutePushQuery(m, &hStreamApiExecutePushQueryServer{stream})
}

type HStreamApi_ExecutePushQueryServer interface {
	Send(*structpb.Struct) error
	grpc.ServerStream
}

type hStreamApiExecutePushQueryServer struct {
	grpc.ServerStream
}

func (x *hStreamApiExecutePushQueryServer) Send(m *structpb.Struct) error {
	return x.ServerStream.SendMsg(m)
}

func _HStreamApi_ExecuteQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).ExecuteQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/ExecuteQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).ExecuteQuery(ctx, req.(*CommandQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_ListQueries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQueriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).ListQueries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/ListQueries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).ListQueries(ctx, req.(*ListQueriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_GetQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).GetQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/GetQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).GetQuery(ctx, req.(*GetQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_TerminateQueries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateQueriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).TerminateQueries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/TerminateQueries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).TerminateQueries(ctx, req.(*TerminateQueriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_DeleteQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).DeleteQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/DeleteQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).DeleteQuery(ctx, req.(*DeleteQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_RestartQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).RestartQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/RestartQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).RestartQuery(ctx, req.(*RestartQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_CreateConnector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConnectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).CreateConnector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/CreateConnector",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).CreateConnector(ctx, req.(*CreateConnectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_ListConnectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConnectorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).ListConnectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/ListConnectors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).ListConnectors(ctx, req.(*ListConnectorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_GetConnector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).GetConnector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/GetConnector",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).GetConnector(ctx, req.(*GetConnectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_DeleteConnector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConnectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).DeleteConnector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/DeleteConnector",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).DeleteConnector(ctx, req.(*DeleteConnectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_PauseConnector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseConnectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).PauseConnector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/PauseConnector",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).PauseConnector(ctx, req.(*PauseConnectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_ResumeConnector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeConnectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).ResumeConnector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/ResumeConnector",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).ResumeConnector(ctx, req.(*ResumeConnectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_LookupConnector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupConnectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).LookupConnector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/LookupConnector",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).LookupConnector(ctx, req.(*LookupConnectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_ListViews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListViewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).ListViews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/ListViews",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).ListViews(ctx, req.(*ListViewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_GetView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).GetView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/GetView",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).GetView(ctx, req.(*GetViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_DeleteView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).DeleteView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/DeleteView",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).DeleteView(ctx, req.(*DeleteViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/ListNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HStreamApi_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HStreamApiServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hstream.server.HStreamApi/GetNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HStreamApiServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HStreamApi_ServiceDesc is the grpc.ServiceDesc for HStreamApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HStreamApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hstream.server.HStreamApi",
	HandlerType: (*HStreamApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _HStreamApi_Echo_Handler,
		},
		{
			MethodName: "CreateStream",
			Handler:    _HStreamApi_CreateStream_Handler,
		},
		{
			MethodName: "DeleteStream",
			Handler:    _HStreamApi_DeleteStream_Handler,
		},
		{
			MethodName: "ListStreams",
			Handler:    _HStreamApi_ListStreams_Handler,
		},
		{
			MethodName: "LookupShard",
			Handler:    _HStreamApi_LookupShard_Handler,
		},
		{
			MethodName: "Append",
			Handler:    _HStreamApi_Append_Handler,
		},
		{
			MethodName: "ListShards",
			Handler:    _HStreamApi_ListShards_Handler,
		},
		{
			MethodName: "CreateShardReader",
			Handler:    _HStreamApi_CreateShardReader_Handler,
		},
		{
			MethodName: "LookupShardReader",
			Handler:    _HStreamApi_LookupShardReader_Handler,
		},
		{
			MethodName: "ReadShard",
			Handler:    _HStreamApi_ReadShard_Handler,
		},
		{
			MethodName: "DeleteShardReader",
			Handler:    _HStreamApi_DeleteShardReader_Handler,
		},
		{
			MethodName: "CreateSubscription",
			Handler:    _HStreamApi_CreateSubscription_Handler,
		},
		{
			MethodName: "ListSubscriptions",
			Handler:    _HStreamApi_ListSubscriptions_Handler,
		},
		{
			MethodName: "CheckSubscriptionExist",
			Handler:    _HStreamApi_CheckSubscriptionExist_Handler,
		},
		{
			MethodName: "DeleteSubscription",
			Handler:    _HStreamApi_DeleteSubscription_Handler,
		},
		{
			MethodName: "LookupSubscription",
			Handler:    _HStreamApi_LookupSubscription_Handler,
		},
		{
			MethodName: "DescribeCluster",
			Handler:    _HStreamApi_DescribeCluster_Handler,
		},
		{
			MethodName: "SendAdminCommand",
			Handler:    _HStreamApi_SendAdminCommand_Handler,
		},
		{
			MethodName: "PerStreamTimeSeriesStats",
			Handler:    _HStreamApi_PerStreamTimeSeriesStats_Handler,
		},
		{
			MethodName: "PerStreamTimeSeriesStatsAll",
			Handler:    _HStreamApi_PerStreamTimeSeriesStatsAll_Handler,
		},
		{
			MethodName: "ExecuteQuery",
			Handler:    _HStreamApi_ExecuteQuery_Handler,
		},
		{
			MethodName: "ListQueries",
			Handler:    _HStreamApi_ListQueries_Handler,
		},
		{
			MethodName: "GetQuery",
			Handler:    _HStreamApi_GetQuery_Handler,
		},
		{
			MethodName: "TerminateQueries",
			Handler:    _HStreamApi_TerminateQueries_Handler,
		},
		{
			MethodName: "DeleteQuery",
			Handler:    _HStreamApi_DeleteQuery_Handler,
		},
		{
			MethodName: "RestartQuery",
			Handler:    _HStreamApi_RestartQuery_Handler,
		},
		{
			MethodName: "CreateConnector",
			Handler:    _HStreamApi_CreateConnector_Handler,
		},
		{
			MethodName: "ListConnectors",
			Handler:    _HStreamApi_ListConnectors_Handler,
		},
		{
			MethodName: "GetConnector",
			Handler:    _HStreamApi_GetConnector_Handler,
		},
		{
			MethodName: "DeleteConnector",
			Handler:    _HStreamApi_DeleteConnector_Handler,
		},
		{
			MethodName: "PauseConnector",
			Handler:    _HStreamApi_PauseConnector_Handler,
		},
		{
			MethodName: "ResumeConnector",
			Handler:    _HStreamApi_ResumeConnector_Handler,
		},
		{
			MethodName: "LookupConnector",
			Handler:    _HStreamApi_LookupConnector_Handler,
		},
		{
			MethodName: "ListViews",
			Handler:    _HStreamApi_ListViews_Handler,
		},
		{
			MethodName: "GetView",
			Handler:    _HStreamApi_GetView_Handler,
		},
		{
			MethodName: "DeleteView",
			Handler:    _HStreamApi_DeleteView_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _HStreamApi_ListNodes_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _HStreamApi_GetNode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamingFetch",
			Handler:       _HStreamApi_StreamingFetch_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ExecutePushQuery",
			Handler:       _HStreamApi_ExecutePushQuery_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "hstream.proto",
}
